kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: web-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.adminer.ressources.storage }}
