---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: mon-secret
  namespace: default
spec:
  encryptedData:
    content: AgCc8R9//kx8Wpw38Bne31ui4hdVW/XqWA7QVi/0OghTxpukj6xjMc+OwjWaiVcFjNVpO/ab7xxC2nuLmj9nUwp5yffiaqzotPV7WlVAFalosTLjJckTuimxrRvCoidf+M830nt8tQqt5dgf1WKiI0/s0xGhhjgJYeZQhfi4dPk55EiTn7tEmy0KA1GTAfgxAjTWl3MHyUDuMZrdekdyLpDQmtKMBMWk3NO9vsUzrniOw9TwCjVKoEQ4wTtwhzAAMwm9fonn10dPAKkEGJd9VOFRJulPJrODgS7MCw2f95LlsmEJ4eQVbiNRGzgCeuq0uFCEcmxMZdxbq9tbnJknYtI5a1QchJ7XDeiZEAojaAES1HXtsqPaOmKrpIAgFc1Pd5p/WUsPTUOC/y/AEqAHB31MvuSPyxT5bhDgbTMKl8Eos1lPj4uKZnz3IRmCtCKvIu3aLhi8QPIas7EGUx1LQJPELnixHnX4J4DrPjBcO7mcaT9mHkJJnPDKvqlU/OPCymd5OJCeKli3WGdLu/Mz5ZECXmN71UY2xGsEp4XuS7N6qNSsvSsxtXcwLlyywslUuGDyOdyLRMYlXIoB0v1e6l91JlwgbFozpbuh1oNukGwjOXmHty8Zc7k2rAKa+/0CfkOj4rrrYUWy9ijEbrFYoPy7M2ciZc1hUgfY65o3XA4X+aoUzYG0EeMqXh+Pdukf37DZRHiMUa/dOmlBRJW9YdYL9J+q0e+m0Q==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: mon-secret
      namespace: default
